
package Ejercicio2;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author alybe
 */
public class BuscarPorPrecio extends javax.swing.JInternalFrame {

    /**
     * Creates new form BuscarPorPrecio
     */
       private DefaultTableModel modelo = new DefaultTableModel(){
        public boolean isCellEditable(int f, int c){
            return false;
        }
    };
    public BuscarPorPrecio() {
        initComponents();
        armarCabecera();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jlBuscarPorPrecio = new javax.swing.JLabel();
        jlEntre = new javax.swing.JLabel();
        jtfPrecio1 = new javax.swing.JTextField();
        jtfPrecio2 = new javax.swing.JTextField();
        jlY = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtPorPrecio = new javax.swing.JTable();

        setClosable(true);

        jlBuscarPorPrecio.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jlBuscarPorPrecio.setText("Listado por Precio");

        jlEntre.setText("Entre:");

        jtfPrecio1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtfPrecio1FocusLost(evt);
            }
        });
        jtfPrecio1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfPrecio1ActionPerformed(evt);
            }
        });

        jtfPrecio2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfPrecio2ActionPerformed(evt);
            }
        });

        jlY.setText("y");

        jtPorPrecio.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Codigo", "Descripcion", "Precio", "Stock", "Rubro"
            }
        ));
        jScrollPane1.setViewportView(jtPorPrecio);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(99, 99, 99)
                        .addComponent(jlEntre)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jtfPrecio1, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(23, 23, 23)
                        .addComponent(jlY, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtfPrecio2, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 417, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(159, 159, 159)
                        .addComponent(jlBuscarPorPrecio)))
                .addContainerGap(41, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jlBuscarPorPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlEntre)
                    .addComponent(jtfPrecio1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfPrecio2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlY))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtfPrecio1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfPrecio1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfPrecio1ActionPerformed

    private void jtfPrecio2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfPrecio2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfPrecio2ActionPerformed

    private void jtfPrecio1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtfPrecio1FocusLost
        try{
            String precio = jtfPrecio1.getText();
            double prec = Double.parseDouble(precio);
        } catch (NumberFormatException e){
            JOptionPane.showMessageDialog(this, "Ingrese un numero valido.");
            jtfPrecio1.requestFocus();
        }             
    }//GEN-LAST:event_jtfPrecio1FocusLost


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel jlBuscarPorPrecio;
    private javax.swing.JLabel jlEntre;
    private javax.swing.JLabel jlY;
    private javax.swing.JTable jtPorPrecio;
    private javax.swing.JTextField jtfPrecio1;
    private javax.swing.JTextField jtfPrecio2;
    // End of variables declaration//GEN-END:variables

        private void armarCabecera(){
        modelo.addColumn("Codigo");
        modelo.addColumn("Descripcion");
        modelo.addColumn("Precio");
        modelo.addColumn("Rubro");
        modelo.addColumn("Stock");
        jtPorPrecio.setModel(modelo);
    }
}
